### ISSUE TITLE
gulp-cssmin is minifying "background: inherit" incorrectly.

### ISSUE THREAD

**Issue by d-oliveros** [chilijung/gulp-cssmin#14]
If I try to minify a file that looks like this:

```css
.something {
	background: inherit;
}
```

I get this:
```css
.something{background:inherit inherit/inherit inherit inherit inherit}
```

which is invalid CSS. 

As a result, no background rule is being used. Do you have any idea why this is happening?
