### ISSUE TITLE
Rounding in transition, may be in other places

### ISSUE THREAD

**Issue by khanamiryan** [chilijung/gulp-cssmin#15]
I have code
```css
.some{
  transition: all 0.4s ease , background-position 0.0001ms;
}
```
which going to
```css
.some{
transition:all .2s ease,background-position 0s;
}
```
